---
services:
   gateway:
      restart: always
      build:
         context: .
         dockerfile: ./apps/backend/gateway/Dockerfile
      environment:
         BACKEND_SERVICE_QUERY: "http://service_query:4001"
         BACKEND_SERVICE_COMMAND: "http://service_command:4002"
      healthcheck:
         interval: 1s
         retries: 3
         start_period: 10s
         test:
            - CMD
            - curl
            - "-f"
            - "http://localhost:4000/v1/healthz"
         timeout: 10s
      ports:
         - "4000:4000"
      depends_on:
         - service_query
         - service_command
      networks:
         - prensa-network
   mongo:
      environment:
         MONGO_INITDB_ROOT_PASSWORD: 1234
         MONGO_INITDB_ROOT_USERNAME: admin
      image: mongo
      expose:
         - 27017
      restart: always
      networks:
         - prensa-network
   service_command:
      restart: always
      build:
         context: .
         dockerfile: ./apps/backend/services/articles-command/Dockerfile
      environment:
         MONGODB_URI: "mongodb://admin:1234@mongo:27017"
      expose:
         - 4002
      depends_on:
         - mongo
      networks:
         - prensa-network
   service_query:
      restart: always
      build:
         context: .
         dockerfile: ./apps/backend/services/articles-query/Dockerfile
      environment:
         MONGODB_URI: "mongodb://admin:1234@mongo:27017"
      expose:
         - 4001
      depends_on:
         - mongo
      networks:
         - prensa-network
   www:
      build:
         context: .
         dockerfile: ./apps/frontend/www/Dockerfile
         args:
            - NEXT_PUBLIC_API_URL=http://localhost:4000
      ports:
         - "3000:3000"
      networks:
         - prensa-network
networks:
   prensa-network:
      driver: bridge
version: "3.1"
