---
services:
   gateway:
      build:
         context: .
         dockerfile: ./apps/backend/gateway/Dockerfile
      environment:
         MONGODB_URI: "mongodb://admin:1234@localhost:27017"
      healthcheck:
         interval: 1s
         retries: 3
         start_period: 10s
         test:
            - CMD
            - curl
            - "-f"
            - "http://localhost:4000/v1/healthz"
         timeout: 10s
      ports:
         - "4000:4000"
   mongo:
      environment:
         MONGO_INITDB_ROOT_PASSWORD: 1234
         MONGO_INITDB_ROOT_USERNAME: admin
      image: mongo
      ports:
         - "27017:27017"
      restart: always
   service_command:
      build:
         context: .
         dockerfile: ./apps/backend/services/articles-command/Dockerfile
      environment:
         MONGODB_URI: "mongodb://admin:1234@localhost:27017"
      ports:
         - "4002:4002"
   service_query:
      build:
         context: .
         dockerfile: ./apps/backend/services/articles-query/Dockerfile
      environment:
         MONGODB_URI: "mongodb://admin:1234@localhost:27017"
      ports:
         - "4001:4001"
   www:
      build:
         context: .
         dockerfile: ./apps/frontend/www/Dockerfile
      environment:
         NEXT_PUBLIC_API_URL: "http://localhost:4000"
      ports:
         - "3000:3000"
version: "3.1"
