#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH="$(git branch --show-current)"

if [ "$SKIP_CHECK" == "true" ]; then
   echo "CAUTION: Skipping pre-push hook"
else
   # if [ "$BRANCH" == "main" ]; then
   #    echo "ERROR: You can't commit to protected main"
   #    exit 1
   # fi

   pnpm frontend-www:build
   pnpm frontend-www-e2e:start
fi
